### PR TITLE
Added changelog for the new version

### PR DESCRIPTION
**Pull request by WisdomPill**
I thought that maybe it is time for a major release because there are a lot of changes.

We might also not do it, it is up for debate.

I did not include #508 but it might be merged before the new release, let's see how it goes

### CODE REVIEW

**Review by terencehonles — APPROVED** [review]
LGTM, we may want to have people add their own entries and use [towncrier](https://towncrier.readthedocs.io/en/actual-freaking-docs/) in the future.

**Comment by WisdomPill** [comment]
Seems like a promising tool, you may want to add the issue and mark as a good frosty issue?

**Comment by terencehonles** [comment]
Done https://github.com/jazzband/django-redis/issues/535

**Comment by WisdomPill** [comment]
Thanks! Everything clear

**Pull request merged**
