### PR TITLE
Update type comments to type annotations

### PR DESCRIPTION
**Pull request by terencehonles**

### CODE REVIEW

**Comment by WisdomPill** [comment]
Why move to type comments? We are already supporting 3.6+ so it should work on all supported python versions

**Comment by terencehonles** [comment]
> Why move to type comments? We are already supporting 3.6+ so it should work on all supported python versions

This *removes* type comments, because it is supported in 3.6+. The type comments are the older syntax.

**Comment by WisdomPill** [comment]
I guess I am stupid, or it's just monday morning

**Comment by terencehonles** [comment]
> I guess I am stupid, or it's just monday morning

Haha, no prob. Maybe not enough coffee yet? :coffee:

**Pull request merged**
