### PR TITLE
Restored redis 4 and master in CI

### PR DESCRIPTION
**Pull request by WisdomPill**

### CODE REVIEW

**Comment by WisdomPill** [comment]
@hartwork do you think we could work around the issue with `packaging` by installing it when using `redis-master`?

**Comment by hartwork** [comment]
> @hartwork do you think we could work around the issue with `packaging` by installing it when using `redis-master`?

@WisdomPill technically yes, but please note https://github.com/jazzband/django-redis/pull/576#issuecomment-992511729 for the bigger picture.

**Review by hartwork — APPROVED** [review]

**Review by hartwork — CHANGES_REQUESTED** [review]
@WisdomPill Installation of package `packaging` seems still missing.
PS: My vote for merging this without squashing.

**Review by hartwork — CHANGES_REQUESTED** [review]
@WisdomPill the way how `packaging` is added right now does not guarantee that it's installed _prior to_ redis-py, which is causing the breakage. If that's not easily fixable, my vote for re-opening #576 and merge that fix in isolation, first.

**Comment by WisdomPill** [comment]
agreed

**Comment by hartwork** [comment]
@WisdomPill thank you!

**Pull request merged**
