### PR TITLE
Preparing release of version 5.1.0

### LINKED ISSUE #562: Roadmap for next release
There are a few new things for the next release already.

Can we discuss on what is blocking the next release? Maybe call it even 5.1.0

I would say to solve the problem with redis-py>=4.0.0 is the only blocker

@terencehonles what do you think?

### PR DESCRIPTION
**Pull request by WisdomPill**
Fixes #562 

Hello all, this is my first release so I am asking you if everything is alright.

I followed [this](https://github.com/jazzband/django-redis/blob/master/RELEASING.rst).

About tagging, I have some doubts, should I push tags to my own fork or here?

I would follow [this](https://git-scm.com/book/en/v2/Git-Basics-Tagging), so the command to execute on my end before pushing should be `git tag -a 5.0.1`.

Can you confirm that?

### CODE REVIEW

**Comment by terencehonles** [comment]
@WisdomPill we probably should make this release `5.1.0` since there are some features and it's not just a bugfix release. As far as the tagging the command you have is good (but would be updated to be `5.1.0`), you can put the changelog description in the tag body and the release version in the tag subject (like a commit the first line is the subject and then a blank and then the description is the rest).

You would then push the tag you created to this repo (you could also push to your fork) `git push --tags <remote>` will do the trick, or you can say `git push <remote> <tag>`.

**Comment by terencehonles** [comment]
Feel free to update the release notes based on your experience preparing the release (you may want to commit after pushing the release via the jazzband site in case there is anything that should be explained there).

**Comment by WisdomPill** [comment]
If anybody could have a look and give some kind of approval I will proceed with the release through the GitHub action listening to newly pushed tags

**Review by terencehonles — APPROVED** [review]
LGTM

**Comment by jezdez** [comment]
@WisdomPill Yeah, you need to tag and push the release to the main repo to trigger the GitHub action that does the release to the Jazzband index. From there the project leads can verify and confirm the release to PyPI.

**Comment by WisdomPill** [comment]
I pushed the [tag 5.1.0](https://github.com/jazzband/django-redis/releases/tag/5.1.0). 
I am one of the project leads, I received three emails, two of them are the same. 
The only difference is that in one the file name is `django_redis-5.1.0-py3-none-any.whl` and the other `django-redis-5.1.0.tar.gz`, should I release both?

**Comment by jezdez** [comment]
> I pushed the [tag 5.1.0](https://github.com/jazzband/django-redis/releases/tag/5.1.0).
> I am one of the project leads, I received three emails, two of them are the same.

Yeah, it's a known issues, disregard one email :)

> The only difference is that in one the file name is `django_redis-5.1.0-py3-none-any.whl` and the other `django-redis-5.1.0.tar.gz`, should I release both?

Both, please.

**Comment by WisdomPill** [comment]
Thanks for the guidance! 
I released the new version! 🎉

**Pull request merged**
