### PR TITLE
pin redis-py to 3.x until 4.x breaking changes can be addressed

### PR DESCRIPTION
**Pull request by terencehonles**

### CODE REVIEW

**Comment by WisdomPill** [comment]
LGTM

**Comment by WisdomPill** [comment]
Is it possibile to not check for coverage on tests directory but only check types in tests directory?

**Comment by terencehonles** [comment]
> Is it possibile to not check for coverage on tests directory but only check types in tests directory?

Is that why it's codecov is complaining? I figured it was not enough typing over there. Let me look at the config.

**Comment by terencehonles** [comment]
It should be excluding the tests:

https://github.com/jazzband/django-redis/blob/9cd2bbeb5039f013abcdd24c1486748676e4c312/setup.cfg#L46-L49

**Comment by terencehonles** [comment]
I think what you're seeing is that Mypy is complaining about any `Any` which the codebase has a lot since anything that's not defined is an `Any`.

**Comment by jacklinke** [comment]
Is there a description of the problem or an associated issue that details what issues `django-redis` has with `redis-py` 4?

**Comment by terencehonles** [comment]
@jacklinke right now what's known is #542. I had created #569 which may have been more clear, but it was closed as a dup of #542.

I understand the problem, but haven't had time to adjust the code. It does seem like it will be a "decent" amount of work because redis 4 separates sentinel and non sentinel connection pools a bit more. This is _probably_ a good thing since you can configure the connection settings more independently, but not how I had written #460 and the code will need a little re-work. After that we would need to look for any other breaking changes and make sure we have sufficient test coverage to make sure expectations continue to be met regardless if breaking changes are documented or not.

**Comment by WisdomPill** [comment]
@terencehonles regarding tests, 
lately I have been contributing a little in `redis-py` and I saw how they are using `tox` with docker for setting up the environment.
I find it very clean since you just need docker running and the test suite will take care of the rest.

Would you mind taking a look and get back to me?
I would like to have something similar in the future

**Comment by terencehonles** [comment]
@WisdomPill do you mind creating a separate issue to discuss and research that? We probably don't need to keep bumping this thread with relation to a change like that.

**Pull request merged**
